name: NutriKids CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [18.19.1]
    env:
      AUTH_SECRET: ${{ secrets.AUTH_SECRET }}
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
      GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
      RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
      NEXT_PUBLIC_APP_URL: ${{ secrets.NEXT_PUBLIC_APP_URL }}
      SMTP_EMAIL: ${{ secrets.SMTP_EMAIL }}
      SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Create .env file
      run: |
        touch .env
        echo AUTH_SECRET=${{ secrets.AUTH_SECRET }} >> .env
        echo DATABASE_URL=${{ secrets.DATABASE_URL }} >> .env
        echo GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }} >> .env
        echo GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }} >> .env
        echo RESEND_API_KEY=${{ secrets.RESEND_API_KEY }} >> .env
        echo NEXT_PUBLIC_APP_URL=${{ secrets.NEXT_PUBLIC_APP_URL }} >> .env
        echo SMTP_EMAIL=${{ secrets.SMTP_EMAIL }} >> .env
        echo SMTP_PASSWORD=${{ secrets.SMTP_PASSWORD }} >> .env
    - run: npm ci
    - run: npm run build --if-present
    - name: Change Directory
      run: cd /home/tharisha/projects/project.tharishaperera.com.lk/actions-runner/_work/final-project-nutrikids/final-project-nutrikids
    - run: pm2 restart 2