name: Playwright Tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Create .env file
      run: |
        touch .env
        echo AUTH_SECRET=${{ secrets.AUTH_SECRET }} >> .env
        echo DATABASE_URL=${{ secrets.DATABASE_URL }} >> .env
        echo GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }} >> .env
        echo GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }} >> .env
        echo RESEND_API_KEY=${{ secrets.RESEND_API_KEY }} >> .env
        echo NEXT_PUBLIC_APP_URL=${{ secrets.NEXT_PUBLIC_APP_URL }} >> .env
        echo SMTP_EMAIL=${{ secrets.SMTP_EMAIL }} >> .env
        echo SMTP_PASSWORD=${{ secrets.SMTP_PASSWORD }} >> .env  
        echo AUTH_TRUST_HOST=${{ secrets.AUTH_TRUST_HOST }} >> .env
        echo DAILY_API_KEY=${{ secrets.DAILY_API_KEY }} >> .env
        echo DAILY_API_URL=${{ secrets.DAILY_API_URL }} >> .env
        echo DEFAULT_USER_PASSWORD=${{ secrets.DEFAULT_USER_PASSWORD }} >> .env
        echo EDGE_STORE_ACCESS_KEY=${{ secrets.EDGE_STORE_ACCESS_KEY }} >> .env
        echo EDGE_STORE_SECRET_KEY=${{ secrets.EDGE_STORE_SECRET_KEY }} >> .env
        echo NEXTAUTH_URL=${{ secrets.NEXTAUTH_URL }} >> .env
        echo TIMESLOT_DURATION=${{ secrets.TIMESLOT_DURATION }} >> .env
        echo TZ=${{ secrets.TZ }} >> .env
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      run: npx playwright test
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
